const pool = require("./db");

/**
 * Script to seed all requested Ads into the MySQL database.
 * Exported so app.js can run it automatically on server startup.
 */
const adsToSeed = [
    // --- HAIR ---
    { ad_name: "Hair Transplant", keyword: "hair transplant", category: "hair" },
    { ad_name: "Digital Trichoscopy", keyword: "digital trichoscopy", category: "hair" },
    { ad_name: "FUE Hair Transplant", keyword: "fue hair transplant", category: "hair" },
    { ad_name: "DHI Hair Transplant", keyword: "dhi hair transplant", category: "hair" },
    { ad_name: "Sapphire FUE", keyword: "sapphire fue", category: "hair" },
    { ad_name: "FIT Hair Transplant", keyword: "fit hair transplant", category: "hair" },
    { ad_name: "No Shave Hair Transplant", keyword: "no shave hair transplant", category: "hair" },
    { ad_name: "Female Hair Transplant", keyword: "female hair transplant", category: "hair" },
    { ad_name: "Hairline Design", keyword: "hairline design", category: "hair" },
    { ad_name: "Hairline Lowering", keyword: "hairline lowering", category: "hair" },
    { ad_name: "Crown Hair Transplant", keyword: "crown hair transplant", category: "hair" },
    { ad_name: "Temple Restoration", keyword: "temple restoration", category: "hair" },
    { ad_name: "Beard Transplant", keyword: "beard transplant", category: "hair" },
    { ad_name: "Mustache Transplant", keyword: "mustache transplant", category: "hair" },
    { ad_name: "Sideburn Transplant", keyword: "sideburn transplant", category: "hair" },
    { ad_name: "Eyebrow Transplant", keyword: "eyebrow transplant", category: "hair" },
    { ad_name: "Body Hair Transplant", keyword: "body hair transplant", category: "hair" },
    { ad_name: "Scar Hair Restoration", keyword: "scar hair restoration", category: "hair" },
    { ad_name: "PRP Hair", keyword: "prp hair", category: "hair" },
    { ad_name: "GFC Hair", keyword: "gfc hair", category: "hair" },
    { ad_name: "Exosome Hair", keyword: "exosome hair", category: "hair" },
    { ad_name: "Stem Cell Hair", keyword: "stem cell hair", category: "hair" },
    { ad_name: "Mesotherapy Hair", keyword: "mesotherapy hair", category: "hair" },
    { ad_name: "Microneedling Hair", keyword: "microneedling hair", category: "hair" },
    { ad_name: "LLLT", keyword: "lllt", category: "hair" },
    { ad_name: "Scalp Detox", keyword: "scalp detox", category: "hair" },
    { ad_name: "Hair Spa Medical", keyword: "hair spa medical", category: "hair" },
    { ad_name: "Anti Dandruff Therapy", keyword: "anti dandruff therapy", category: "hair" },
    { ad_name: "Seborrheic Dermatitis Therapy", keyword: "seborrheic dermatitis therapy", category: "hair" },
    { ad_name: "Scalp Psoriasis Therapy", keyword: "scalp psoriasis therapy", category: "hair" },
    { ad_name: "Alopecia Areata Therapy", keyword: "alopecia areata therapy", category: "hair" },
    { ad_name: "Hair Booster", keyword: "hair booster", category: "hair" },
    { ad_name: "QR678 Therapy", keyword: "qr678 therapy", category: "hair" },
    { ad_name: "Growth Factor Booster", keyword: "growth factor booster", category: "hair" },
    { ad_name: "Scalp Micropigmentation", keyword: "scalp micropigmentation", category: "hair" },
    { ad_name: "Hair Density Treatment", keyword: "hair density treatment", category: "hair" },
    { ad_name: "Post Transplant PRP", keyword: "post transplant prp", category: "hair" },
    { ad_name: "Laser Cap Therapy", keyword: "laser cap therapy", category: "hair" },
    { ad_name: "Hair Analysis", keyword: "hair analysis", category: "hair" },
    { ad_name: "Hair Nutrition Consultation", keyword: "hair nutrition consultation", category: "hair" },

    // --- SKIN / FACIALS / LASERS / INJECTABLES ---
    { ad_name: "HydraFacial Signature", keyword: "hydrafacial signature", category: "skin" },
    { ad_name: "HydraFacial Deluxe", keyword: "hydrafacial deluxe", category: "skin" },
    { ad_name: "HydraFacial Platinum", keyword: "hydrafacial platinum", category: "skin" },
    { ad_name: "Oxygeneo Facial", keyword: "oxygeneo facial", category: "skin" },
    { ad_name: "Fire & Ice Facial", keyword: "fire & ice facial", category: "skin" },
    { ad_name: "Carbon Facial", keyword: "carbon facial", category: "skin" },
    { ad_name: "Gold Facial", keyword: "gold facial", category: "skin" },
    { ad_name: "Diamond Facial", keyword: "diamond facial", category: "skin" },
    { ad_name: "Oxygen Facial", keyword: "oxygen facial", category: "skin" },
    { ad_name: "Korean Glass Facial", keyword: "korean glass facial", category: "skin" },
    { ad_name: "Chemical Peel", keyword: "chemical peel", category: "skin" },
    { ad_name: "Salicylic Peel", keyword: "salicylic peel", category: "skin" },
    { ad_name: "Glycolic Peel", keyword: "glycolic peel", category: "skin" },
    { ad_name: "Yellow Peel", keyword: "yellow peel", category: "skin" },
    { ad_name: "TCA Peel", keyword: "tca peel", category: "skin" },
    { ad_name: "Carbon Laser Peel", keyword: "carbon laser peel", category: "skin" },
    { ad_name: "Laser Toning", keyword: "laser toning", category: "skin" },
    { ad_name: "Q Switch Laser", keyword: "q switch laser", category: "skin" },
    { ad_name: "Pico Laser", keyword: "pico laser", category: "skin" },
    { ad_name: "Fractional CO2", keyword: "fractional co2", category: "skin" },
    { ad_name: "IPL Photofacial", keyword: "ipl photofacial", category: "skin" },
    { ad_name: "Microneedling", keyword: "microneedling", category: "skin" },
    { ad_name: "RF Microneedling", keyword: "rf microneedling", category: "skin" },
    { ad_name: "PRP Facial", keyword: "prp facial", category: "skin" },
    { ad_name: "GFC Facial", keyword: "gfc facial", category: "skin" },
    { ad_name: "Skin Booster", keyword: "skin booster", category: "skin" },
    { ad_name: "Profhilo", keyword: "profhilo", category: "skin" },
    { ad_name: "Jalupro", keyword: "jalupro", category: "skin" },
    { ad_name: "Rejuran", keyword: "rejuran", category: "skin" },
    { ad_name: "Polynucleotide Therapy", keyword: "polynucleotide therapy", category: "skin" },
    { ad_name: "Glutathione Facial", keyword: "glutathione facial", category: "skin" },
    { ad_name: "Acne Treatment", keyword: "acne treatment", category: "skin" },
    { ad_name: "Acne Scar", keyword: "acne scar", category: "skin" },
    { ad_name: "Subcision", keyword: "subcision", category: "skin" },
    { ad_name: "TCA Cross", keyword: "tca cross", category: "skin" },
    { ad_name: "Punch Excision", keyword: "punch excision", category: "skin" },
    { ad_name: "Pigmentation Treatment", keyword: "pigmentation treatment", category: "skin" },
    { ad_name: "Melasma Treatment", keyword: "melasma treatment", category: "skin" },
    { ad_name: "Freckles Treatment", keyword: "freckles treatment", category: "skin" },
    { ad_name: "Dark Circle", keyword: "dark circle", category: "skin" },
    { ad_name: "Under Eye PRP", keyword: "under eye prp", category: "skin" },
    { ad_name: "Skin Brightening", keyword: "skin brightening", category: "skin" },
    { ad_name: "Anti Aging Program", keyword: "anti aging program", category: "skin" },
    { ad_name: "Botox", keyword: "botox", category: "skin" },
    { ad_name: "Baby Botox", keyword: "baby botox", category: "skin" },
    { ad_name: "Lip Flip", keyword: "lip flip", category: "skin" },
    { ad_name: "Masseter Botox", keyword: "masseter botox", category: "skin" },
    { ad_name: "Hyperhidrosis Botox", keyword: "hyperhidrosis botox", category: "skin" },
    { ad_name: "Lip Filler", keyword: "lip filler", category: "skin" },
    { ad_name: "Chin Filler", keyword: "chin filler", category: "skin" },
    { ad_name: "Jawline Filler", keyword: "jawline filler", category: "skin" },
    { ad_name: "Cheek Filler", keyword: "cheek filler", category: "skin" },
    { ad_name: "Temple Filler", keyword: "temple filler", category: "skin" },
    { ad_name: "Nose Filler", keyword: "nose filler", category: "skin" },
    { ad_name: "Thread Lift", keyword: "thread lift", category: "skin" },
    { ad_name: "HIFU", keyword: "hifu", category: "skin" },
    { ad_name: "RF Tightening", keyword: "rf tightening", category: "skin" },
    { ad_name: "Mole Removal", keyword: "mole removal", category: "skin" },
    { ad_name: "Wart Removal", keyword: "wart removal", category: "skin" },
    { ad_name: "Skin Tag Removal", keyword: "skin tag removal", category: "skin" },
    { ad_name: "Milia Removal", keyword: "milia removal", category: "skin" },
    { ad_name: "Corn Removal", keyword: "corn removal", category: "skin" },
    { ad_name: "Xanthelasma Removal", keyword: "xanthelasma removal", category: "skin" },
    { ad_name: "Syringoma Removal", keyword: "syringoma removal", category: "skin" },
    { ad_name: "Lipoma Removal", keyword: "lipoma removal", category: "skin" },
    { ad_name: "Sebaceous Cyst Removal", keyword: "sebaceous cyst removal", category: "skin" },
    { ad_name: "Keloid Injection", keyword: "keloid injection", category: "skin" },
    { ad_name: "Stretch Mark Treatment", keyword: "stretch mark treatment", category: "skin" },
    { ad_name: "Scar Revision", keyword: "scar revision", category: "skin" },
    { ad_name: "Vitiligo Camouflage", keyword: "vitiligo camouflage", category: "skin" },
    { ad_name: "Upper Lip", keyword: "upper lip", category: "skin" },
    { ad_name: "Chin", keyword: "chin", category: "skin" },
    { ad_name: "Side Locks", keyword: "side locks", category: "skin" },
    { ad_name: "Neck", keyword: "neck", category: "skin" },
    { ad_name: "Full Face", keyword: "full face", category: "skin" },
    { ad_name: "Underarms", keyword: "underarms", category: "skin" },
    { ad_name: "Half Arms", keyword: "half arms", category: "skin" },
    { ad_name: "Full Arms", keyword: "full arms", category: "skin" },
    { ad_name: "Half Legs", keyword: "half legs", category: "skin" },
    { ad_name: "Full Legs", keyword: "full legs", category: "skin" },
    { ad_name: "Chest", keyword: "chest", category: "skin" },
    { ad_name: "Abdomen", keyword: "abdomen", category: "skin" },
    { ad_name: "Back", keyword: "back", category: "skin" },
    { ad_name: "Shoulders", keyword: "shoulders", category: "skin" },
    { ad_name: "Bikini", keyword: "bikini", category: "skin" },
    { ad_name: "Brazilian", keyword: "brazilian", category: "skin" },
    { ad_name: "Buttocks", keyword: "buttocks", category: "skin" },
    { ad_name: "Fingers", keyword: "fingers", category: "skin" },
    { ad_name: "Toes", keyword: "toes", category: "skin" },
    { ad_name: "Full Body", keyword: "full body", category: "skin" },
    { ad_name: "Tattoo Removal", keyword: "tattoo removal", category: "skin" },
    { ad_name: "Laser Vein Removal", keyword: "laser vein removal", category: "skin" },
    { ad_name: "Laser Nail Fungus", keyword: "laser nail fungus", category: "skin" },
    { ad_name: "Laser Skin Rejuvenation", keyword: "laser skin rejuvenation", category: "skin" },
    { ad_name: "Laser Scar Reduction", keyword: "laser scar reduction", category: "skin" },
    { ad_name: "Laser Birthmark", keyword: "laser birthmark", category: "skin" },

    // --- PMU (PERMANENT MAKEUP) ---
    { ad_name: "Microblading", keyword: "microblading", category: "pmu" },
    { ad_name: "Ombre Brows", keyword: "ombre brows", category: "pmu" },
    { ad_name: "Combination Brows", keyword: "combination brows", category: "pmu" },
    { ad_name: "Nano Brows", keyword: "nano brows", category: "pmu" },
    { ad_name: "Powder Brows", keyword: "powder brows", category: "pmu" },
    { ad_name: "Hyperreal Brows", keyword: "hyperreal brows", category: "pmu" },
    { ad_name: "Lip Blush", keyword: "lip blush", category: "pmu" },
    { ad_name: "Lip Neutralization", keyword: "lip neutralization", category: "pmu" },
    { ad_name: "Lip Tint", keyword: "lip tint", category: "pmu" },
    { ad_name: "Dark Lip Correction", keyword: "dark lip correction", category: "pmu" },
    { ad_name: "Permanent Eyeliner", keyword: "permanent eyeliner", category: "pmu" },
    { ad_name: "Lash Enhancement", keyword: "lash enhancement", category: "pmu" },
    { ad_name: "Beard Micropigmentation", keyword: "beard micropigmentation", category: "pmu" },
    { ad_name: "Scar Camouflage", keyword: "scar camouflage", category: "pmu" },
    { ad_name: "Stretch Mark Camouflage", keyword: "stretch mark camouflage", category: "pmu" },
    { ad_name: "Areola Reconstruction", keyword: "areola reconstruction", category: "pmu" },
    { ad_name: "Beauty Spot", keyword: "beauty spot", category: "pmu" },
    { ad_name: "Freckle Tattoo", keyword: "freckle tattoo", category: "pmu" },
    { ad_name: "PMU Removal", keyword: "pmu removal", category: "pmu" },
    { ad_name: "PMU Color Correction", keyword: "pmu color correction", category: "pmu" },
    { ad_name: "Touch Up", keyword: "touch up", category: "pmu" },
    { ad_name: "Correction Session", keyword: "correction session", category: "pmu" },

    // --- WEIGHT LOSS & IV THERAPIES ---
    { ad_name: "Body Composition", keyword: "body composition", category: "weight_loss" },
    { ad_name: "Medical Weight Loss", keyword: "medical weight loss", category: "weight_loss" },
    { ad_name: "GLP-1 Program", keyword: "glp-1 program", category: "weight_loss" },
    { ad_name: "Ozempic Program", keyword: "ozempic program", category: "weight_loss" },
    { ad_name: "Mounjaro Program", keyword: "mounjaro program", category: "weight_loss" },
    { ad_name: "Saxenda Program", keyword: "saxenda program", category: "weight_loss" },
    { ad_name: "Diet Consultation", keyword: "diet consultation", category: "weight_loss" },
    { ad_name: "Nutrition Program", keyword: "nutrition program", category: "weight_loss" },
    { ad_name: "Metabolic Assessment", keyword: "metabolic assessment", category: "weight_loss" },
    { ad_name: "EMS Sculpt", keyword: "ems sculpt", category: "weight_loss" },
    { ad_name: "Cavitation", keyword: "cavitation", category: "weight_loss" },
    { ad_name: "RF Body Tightening", keyword: "rf body tightening", category: "weight_loss" },
    { ad_name: "Cryolipolysis", keyword: "cryolipolysis", category: "weight_loss" },
    { ad_name: "Fat Dissolving Injection", keyword: "fat dissolving injection", category: "weight_loss" },
    { ad_name: "Double Chin Reduction", keyword: "double chin reduction", category: "weight_loss" },
    { ad_name: "Cellulite Reduction", keyword: "cellulite reduction", category: "weight_loss" },
    { ad_name: "Lymphatic Drainage", keyword: "lymphatic drainage", category: "weight_loss" },
    { ad_name: "Body Detox", keyword: "body detox", category: "weight_loss" },
    { ad_name: "Inch Loss Program", keyword: "inch loss program", category: "weight_loss" },
    { ad_name: "Post Pregnancy Contouring", keyword: "post pregnancy contouring", category: "weight_loss" },
    { ad_name: "Skin Tightening", keyword: "skin tightening", category: "weight_loss" },
    { ad_name: "Wellness IV", keyword: "wellness iv", category: "weight_loss" },
    { ad_name: "Vitamin C IV", keyword: "vitamin c iv", category: "weight_loss" },
    { ad_name: "Glutathione IV", keyword: "glutathione iv", category: "weight_loss" },
    { ad_name: "NAD+ Therapy", keyword: "nad+ therapy", category: "weight_loss" },
    { ad_name: "Energy Booster IV", keyword: "energy booster iv", category: "weight_loss" },
    { ad_name: "Hair IV", keyword: "hair iv", category: "weight_loss" },
    { ad_name: "Immunity IV", keyword: "immunity iv", category: "weight_loss" },
    { ad_name: "Weight Maintenance Program", keyword: "weight maintenance program", category: "weight_loss" },

    // --- GENERAL / CONSULTATION ---
    { ad_name: "Consultation", keyword: "consultation", category: "general" }
];

async function seedAds() {
    try {
        let count = 0;
        for (const ad of adsToSeed) {
            await pool.execute(
                `INSERT INTO ads (ad_name, keyword, category, status)
                 VALUES (?, ?, ?, 'active')
                 ON DUPLICATE KEY UPDATE
                    ad_name = VALUES(ad_name),
                    category = VALUES(category),
                    status = 'active'`,
                [ad.ad_name, ad.keyword, ad.category]
            );
            count++;
        }
        console.log(`✓ Automatically verified ${count} Ads in database.`);
    } catch (err) {
        console.error("Error auto-seeding ads:", err.message);
    }
}

module.exports = seedAds;

if (require.main === module) {
    seedAds().then(() => pool.end());
}
